### ISSUE TITLE
Clarify rename message?

### ISSUE THREAD

**Issue by henrik** [ManageIQ/optimist#104]
I saw this deprecation message: "[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible."

But nothing in that message says which gem has been renamed. It wasn't hard to google the message, but if it's easy enough to push a new version of trollop, maybe it could be worth clarifying by changing "This gem" to "The trollop gem".

**Comment by kbrock** [comment]
@Fryguy I created the branch, but didn't have a place to merge into.

Do you want to create a branch ( @ 2.9.9) so we can merge in this message change?

I was thinking:

```diff
-warn "[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible."
+warn "[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible."
```

**Comment by Fryguy** [comment]
Sounds good to me @kbrock

**Comment by kbrock** [comment]
@kbrock I'm not sure how to submit a PR for this. I don't know how to target `trollop` and target that branch. (can we create a `trollop_stable` branch or something?

**Comment by Fryguy** [comment]
You can probably just push the commit directly...no need for a PR as we've discussed the wording here.

**Comment by kbrock** [comment]
thanks for your help
