### ISSUE TITLE
Rename operation: how to deal with legacy code?

### ISSUE THREAD

**Issue by rubyFeedback** [ManageIQ/optimist#106]
Hello,

I am maintaining legacy code written by someone else quite some years ago, in trollop.

I have just seen the message on the commandline that trollop is now called optimist.

I have no problem with this per se, but I would like to know how difficult it may be to rewrite trollop-code in optimist. Right now I have no idea.

Would it be possible to add a subsection to the main readme? It does not have to be a long paragraph, just something that tells people who may be in a similar position as I am, how easy the rewrite operation may be. For example, would replacing all of Trollop with Optimist in the code as-is, continue to work? And if not, how to know how to replace it with?

Right now I am not sure how to proceed, since I was not the one who wrote the original code there. I would ideally like to invest as little time as possible :) but if it requires a larger rewrite then I am more inclined to just use ARGV directly since that is simpler; not as elegant and useful, but simpler for me in regards to maintaining the legacy code. (Rewriting the whole legacy code would take even longer ... sorry for that comment, I am just trying to be honest. As said the ideal situation would be for me to only have to e. g. replace require 'trollop' with require 'optimist', and replacing all Trollop with Optimist, but right now I just don't know, which is why a little helpful intro may help).

Thanks for reading.

**Comment by nanobowers** [comment]
AFAIK, this:
> ... the ideal situation would be for me to only have to e. g. replace require 'trollop' with require 'optimist', and replacing all Trollop with Optimist

is all you need to do.  Other than new features, I cannot think of anything else that would break backward compatibility.
