### ISSUE TITLE
Consider merging in optimist_xl

### ISSUE THREAD

**Issue by nanobowers** [ManageIQ/optimist#115]
Would kindly suggest to merge in the changes in the Optimist_XL gem, which is a feature enhancement fork.  Also, it addresses #88 and #97, plus some closed-but-unresolved issues.

https://github.com/nanobowers/optimist_xl

**Comment by Fryguy** [comment]
@kbrock - Let's review: https://github.com/nanobowers/optimist_xl#extended-features-unavailable-in-the-original-optimist-gem

**Comment by Fryguy** [comment]
This is awesome work @nanobowers!  I am kind of swamped coming back from break, but hopefully I can eyeball this in the coming week.

**Comment by kbrock** [comment]
Thank you for your patience and thanks for forking this to show us how many of your great ideas work

**Comment by Fryguy** [comment]
@nanobowers If you're up for it, can you make some PRs to get the core functionality of optimist XL into optimist?  As you said in the other PR, not every feature in optimist XL is for everyone, but I do believe _most_ features are for everyone.  If you can make a PR per feature we can debate those independently, and I would presume most would make it after discussion.

**Comment by Fryguy** [comment]
Alternatively maybe we can resurrect (or redo) #116 .  I can't recall what we stalled on...something about chronic gem it seems?

**Comment by nanobowers** [comment]
> Alternatively maybe we can resurrect (or redo) #116 . I can't recall what we stalled on...something about chronic gem it seems?

@Fryguy IIRC I caused a breaking change due to chronic support.  I have never been a fan of the hidden "if you happen to have this other gem installed you get completely different behavior" and pulled it into a separate file so one would have to `require "optimist/chronic"` to explicitly call out that chronic style behavior was desired.  But then that violated the single-file rule which has existed since the beginning...   I'll close this and #116 and piece-part out a bunch of PRs.
