### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nanobowers** [ManageIQ/optimist#162]
The (last) 3.1.0 release was over a year ago and there have been a lot of updates since then.
Can we make a new versioned release / gem build?

@Fryguy

**Comment by Fryguy** [comment]
Yes - I wasn't sure if you wanted any other things in before the next release.  I'm ready to go if you are.

**Comment by Fryguy** [comment]
BTW, I enabled GitHub Discussions on this repo just now so in the future we can have place to discuss things like this.

**Comment by nanobowers** [comment]
Nope, I'm all out of fresh ideas.  Will use the Discussions page next time.  Cheers!

**Comment by nanobowers** [comment]
Moving to the discussions area

**Comment by Fryguy** [comment]
Released 3.2.0
