### ISSUE TITLE
Redirect/delete the rubyforge info page

### ISSUE THREAD

**Issue by dottorblaster** [ManageIQ/optimist#71]
Hi,
Googling for Trollop gives back an old version of the trollop web page, this specifically: http://trollop.rubyforge.org/

I think it's confusing to see multiple web pages, one up to date and one with references to the old git repo (gitorious one). Can someone do something about it? The rubyforge page should be a 301 redirect to http://manageiq.github.io/trollop/, or be deleted.

**Comment by Fryguy** [comment]
I've noticed this myself but I don't know how.  I'm not sure who
runs/maintains rubyforge.  Do you know?

**Comment by dottorblaster** [comment]
Tried to tweet, got no response. Still trying to look around if someone can do this :+1:
