### ISSUE TITLE
date handling: failing tests, chronic causes different behavior

### ISSUE THREAD

**Issue by nanobowers** [ManageIQ/optimist#76]
I got test failures when i ran, caused by issues in the Date handling.
The tests are providing U.S. formatted dates (e.g. 5/1/2010) but Date.parse expects Day/Month/Year format like is used in the E.U.
bypassing that test, the 'today' in test_date_formatting also caused breakage.
Both of these were fixed by installing the chronic gem.

I don't know the history behind this, so maybe this is intentional, but IMHO, an optional dependency shouldn't change existing functionality.  Perhaps another way to handle could be a way to register a field (e.g. "%m/%d/%Y", "%Y/%m/%d", etc) for use with Time.strptime, though that would break the relative time feature that Chronic adds.

**Comment by Mr-Tao** [comment]
I second this. As chronic is optional 6d45d0ea19af0d6e0242ad1f8fe35aeeabfda0ca test should be passing without it being installed.

I’ve filed separate https://github.com/ManageIQ/trollop/issues/86 before I’ve noticed this issue already mentions problem with failing tests.

**Comment by kbrock** [comment]
This is tricky.
We need the gem installed to run the tests.

So it will be tricky to run tests that fail if the gem is not installed

There is the `american_date` gem that swaps that date order as well.
Many programming languages (and government agencies) have confusion around `%m/%d/%y` vs `%d/%m/%y`

**Comment by Mr-Tao** [comment]
@kbrock ic, perhaps an explicit message that tests are failing due to a missing gem would suffice. Trollop 1.2.1 was [masked in Gentoo](https://bugs.gentoo.org/show_bug.cgi?id=625516) with recent Ruby versions simply because maintainer didn’t investigate deep enough.

**Comment by nanobowers** [comment]
#parse_data_parameter tries to load chronic and if it fail to load, then the Date behavior of Trollop is "normal".  Maybe the tests either need to have chronic as a hard dependency, or bypass the tests that would fail if chronic was not available.

Again, i'm not really a big fan of the behavior changing based on existence of another installed gem - in a group environment (e.g. a University), someone may install a gem (chronic) into a "global" Ruby install and then all of the sudden command line tools that use Trollop would start behaving oddly.  That would be pretty hard to track down. :confused:
